# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ebcfbe7b4e28311e381bc8c51b5675ea9eb012578ef74cab80d90b0e234b0939c5675c88ae925dfccf9475c0210971e2810323da2eae3a7cc2e584c3f58ac8

test:
  secret_key_base: d5c6b47053156175c5b60516259fa76b7d378ce020a03bfbbb5e0eeedb83c19e9904ca5964b3996d4f5f6091f621305dca07ece135ed1122263ac19553bc712d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
